name = "cf-websockets"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "930ee94c5320c477a77b76445444be44"
workers_dev = true

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" },
  { name = "limiters", class_name = "RateLimiter" }
]
